version: "3.8"

services:

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbit-host
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - receiver-net

  receiver:
    image: receiver-spring-rabbitmq:1.0
    networks:
      a00_ext:

networks:
  receiver-net:
    driver: bridge