FROM eclipse-temurin:19-jdk

WORKDIR /home/app/src/main/java/it/unisalento/prototype/prototyperabbitmq

COPY . /home/app

CMD ["java", "-jar", "build/libs/PrototypeSubPub-rabbitmq-0.0.1-SNAPSHOT.jar"]